#!/bin/bash

objects="./.objects"

function buckets {
    (for x in 1-2 3-4 5-6; do echo "$1" | cut -c $x; done) | paste -s -d / -
}

function same {
    [ "$(stat -f '%i %d' $1)" = "$(stat -f '%i %d' $2)" ]
}

function check {
    file=$1
    h=$(shasum "$file" | cut -c 1-40)
    dir=$objects/$(buckets "$h")
    if [ -e "$dir/$h" ]; then
        if same "$file" "$dir/$h"; then
            echo "Ok. $file already linked to $dir/$h"
        else
            echo "Oops. $file not linked to $dir/$h"
        fi
    else
        echo "Oops. $dir/$h doesn't exist."
    fi
}

while read -r f; do
    check "$f";
done
