#!/bin/bash

objects="./.objects"

function buckets {
    (for x in 1-2 3-4 5-6; do echo "$1" | cut -c $x; done) | paste -s -d / -
}

function restore {
    line=$1
    obj=$(echo "$line" | cut -d $'\t' -f 1)
    file=$(echo "$line" | cut -d $'\t' -f 2)

    echo -n "Restoring $file ..."
    if [ -e "$obj" ]; then
        dir=$(dirname "$file")
        mkdir -p "$dir"
        ln -f "$obj" "$file"
        echo " ok."
    else
        echo " object file $obj does not exist!"
    fi
}

while read -r line; do
    restore "$line";
done
